Add checks for github secrets in test workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,20 +11,27 @@ env:
 
 jobs:
   test:
-    name: test workflow initialization
+    name: Verify github secrets are set
     runs-on: ubuntu-latest
     steps:
       - name: Print start message
         run: echo "Starting test"
 
-      - name: Check env vars
+      - name: Check for github secrets
         run: |
-          if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
-            echo "AWS_REGION is not set"
-            exit 1
-          else
-            echo "AWS_REGION is set"
-          fi
+          secrets=(
+            ${{ secrets.AWS_REGION }}
+            ${{ secrets.AWS_ACCESS_KEY_ID }}
+            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            ${{ secrets.AWS_SAGEMAKER_ENDPOINT }}
+          )
+
+          for secret in "$secrets[@]"; do
+            if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
+              echo "Missing github secrets"
+              exit 1
+            fi
+          done
       
   deploy:
     needs: test
